stages:
  - build
  - test
  - deploy

image: node:16

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run test

deploy_production:
  stage: deploy
  script:
    - echo "Canlıya dağıtım başlatılıyor..."
    # Örneğin, SSH ile canlı sunucuya deploy yapabilirsiniz
    # Örnek:
    - scp -r dist/* user@your-server:/path/to/production
  only:
    - master
